server:
  port: 8992
  tomcat:
    accesslog:
      buffered: false
      directory: /Users/yunzhifei/Downloads/logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8
  thymeleaf:
    mode: HTML5
    cache: false
  profiles:
    include: config



