server:
  port: 8992
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: a19940129
  thymeleaf:
    mode: HTML5
    cache: false
mybatis:
  mapper-locations: classpath:mappers/*.xml